/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as TemplatesCplCpaRouteImport } from './routes/templates.cpl-cpa'
import { Route as TemplatesRnpRouteImport } from './routes/templates.rnp'
import { Route as TemplatesWeeklyReportRouteImport } from './routes/templates.weekly-report'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesCplCpaRoute = TemplatesCplCpaRouteImport.update({
  id: '/templates/cpl-cpa',
  path: '/templates/cpl-cpa',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRnpRoute = TemplatesRnpRouteImport.update({
  id: '/templates/rnp',
  path: '/templates/rnp',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesWeeklyReportRoute = TemplatesWeeklyReportRouteImport.update({
  id: '/templates/weekly-report',
  path: '/templates/weekly-report',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/templates/cpl-cpa': typeof TemplatesCplCpaRoute
  '/templates/rnp': typeof TemplatesRnpRoute
  '/templates/weekly-report': typeof TemplatesWeeklyReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/templates/cpl-cpa': typeof TemplatesCplCpaRoute
  '/templates/rnp': typeof TemplatesRnpRoute
  '/templates/weekly-report': typeof TemplatesWeeklyReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/templates/cpl-cpa': typeof TemplatesCplCpaRoute
  '/templates/rnp': typeof TemplatesRnpRoute
  '/templates/weekly-report': typeof TemplatesWeeklyReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/templates/cpl-cpa'
    | '/templates/rnp'
    | '/templates/weekly-report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/templates/cpl-cpa'
    | '/templates/rnp'
    | '/templates/weekly-report'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/templates/cpl-cpa'
    | '/templates/rnp'
    | '/templates/weekly-report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  TemplatesCplCpaRoute: typeof TemplatesCplCpaRoute
  TemplatesRnpRoute: typeof TemplatesRnpRoute
  TemplatesWeeklyReportRoute: typeof TemplatesWeeklyReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/cpl-cpa': {
      id: '/templates/cpl-cpa'
      path: '/templates/cpl-cpa'
      fullPath: '/templates/cpl-cpa'
      preLoaderRoute: typeof TemplatesCplCpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/rnp': {
      id: '/templates/rnp'
      path: '/templates/rnp'
      fullPath: '/templates/rnp'
      preLoaderRoute: typeof TemplatesRnpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/weekly-report': {
      id: '/templates/weekly-report'
      path: '/templates/weekly-report'
      fullPath: '/templates/weekly-report'
      preLoaderRoute: typeof TemplatesWeeklyReportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  TemplatesCplCpaRoute: TemplatesCplCpaRoute,
  TemplatesRnpRoute: TemplatesRnpRoute,
  TemplatesWeeklyReportRoute: TemplatesWeeklyReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
